export interface BashCommandItem {
  label: string;
  rule: string;
  risk?: 'normal' | 'wide' | 'high';
}

export interface BashCommandGroup {
  id: string;
  title: string;
  description: string;
  order: number;
  selectAllLabel: string;
  commands: BashCommandItem[];
}

export const BASH_COMMAND_GROUPS: BashCommandGroup[] = [
  {
    id: 'basic',
    title: '常用基础命令',
    description: '常用基础命令',
    order: 1,
    selectAllLabel: '常用基础命令',
    commands: [
      { label: 'awk', rule: 'Bash(awk *)' },
      { label: 'cat', rule: 'Bash(cat *)' },
      { label: 'cut', rule: 'Bash(cut *)' },
      { label: 'date', rule: 'Bash(date)' },
      { label: 'df', rule: 'Bash(df *)' },
      { label: 'diff', rule: 'Bash(diff *)' },
      { label: 'du', rule: 'Bash(du *)' },
      { label: 'du -sh', rule: 'Bash(du -sh *)' },
      { label: 'echo', rule: 'Bash(echo *)' },
      { label: 'env', rule: 'Bash(env)' },
      { label: 'file', rule: 'Bash(file *)' },
      { label: 'find .', rule: 'Bash(find . *)' },
      { label: 'find . -maxdepth', rule: 'Bash(find . -maxdepth *)' },
      { label: 'grep', rule: 'Bash(grep *)' },
      { label: 'grep -R', rule: 'Bash(grep -R *)' },
      { label: 'gunzip', rule: 'Bash(gunzip *)' },
      { label: 'gzip', rule: 'Bash(gzip *)' },
      { label: 'head', rule: 'Bash(head *)' },
      { label: 'less', rule: 'Bash(less *)' },
      { label: 'ls', rule: 'Bash(ls *)' },
      { label: 'ls -la', rule: 'Bash(ls -la)' },
      { label: 'ls -lh', rule: 'Bash(ls -lh)' },
      { label: 'mkdir', rule: 'Bash(mkdir *)' },
      { label: 'mkdir -p', rule: 'Bash(mkdir -p *)' },
      { label: 'printenv', rule: 'Bash(printenv *)' },
      { label: 'pwd', rule: 'Bash(pwd)' },
      { label: 'rg', rule: 'Bash(rg *)' },
      { label: 'sed', rule: 'Bash(sed *)' },
      { label: 'sort', rule: 'Bash(sort *)' },
      { label: 'stat', rule: 'Bash(stat *)' },
      { label: 'tail', rule: 'Bash(tail *)' },
      { label: 'tar -cjvf', rule: 'Bash(tar -cjvf *)' },
      { label: 'tar -czvf', rule: 'Bash(tar -czvf *)' },
      { label: 'tar -tzf', rule: 'Bash(tar -tzf *)' },
      { label: 'tar -xjvf', rule: 'Bash(tar -xjvf *)' },
      { label: 'tar -xzvf', rule: 'Bash(tar -xzvf *)' },
      { label: 'tee', rule: 'Bash(tee *)' },
      { label: 'tree', rule: 'Bash(tree *)' },
      { label: 'tr', rule: 'Bash(tr *)' },
      { label: 'uname', rule: 'Bash(uname *)' },
      { label: 'uniq', rule: 'Bash(uniq *)' },
      { label: 'unzip', rule: 'Bash(unzip *)' },
      { label: 'wc', rule: 'Bash(wc *)' },
      { label: 'whereis', rule: 'Bash(whereis *)' },
      { label: 'which', rule: 'Bash(which *)' },
      { label: 'whoami', rule: 'Bash(whoami)' },
      { label: 'xargs', rule: 'Bash(xargs *)' },
      { label: 'zip', rule: 'Bash(zip *)' },
    ],
  },
  {
    id: 'node-npm',
    title: 'Node / npm',
    description: 'Node / npm',
    order: 2,
    selectAllLabel: 'Node / npm',
    commands: [
      { label: 'node --version', rule: 'Bash(node --version)' },
      { label: 'npm --version', rule: 'Bash(npm --version)' },
      { label: 'npm init', rule: 'Bash(npm init *)' },
      { label: 'npm install', rule: 'Bash(npm install)' },
      { label: 'npm install *', rule: 'Bash(npm install *)' },
      { label: 'npm ci', rule: 'Bash(npm ci)' },
      { label: 'npm ci *', rule: 'Bash(npm ci *)' },
      { label: 'npm run', rule: 'Bash(npm run)' },
      { label: 'npm run *', rule: 'Bash(npm run *)' },
      { label: 'npm test', rule: 'Bash(npm test)' },
      { label: 'npm test *', rule: 'Bash(npm test *)' },
      { label: 'npm start', rule: 'Bash(npm start)' },
      { label: 'npm start *', rule: 'Bash(npm start *)' },
      { label: 'npm build *', rule: 'Bash(npm build *)' },
      { label: 'npm list *', rule: 'Bash(npm list *)' },
      { label: 'npm ls *', rule: 'Bash(npm ls *)' },
      { label: 'npm view *', rule: 'Bash(npm view *)' },
      { label: 'npm outdated *', rule: 'Bash(npm outdated *)' },
      { label: 'npm audit', rule: 'Bash(npm audit)' },
      { label: 'npm audit *', rule: 'Bash(npm audit *)' },
      { label: 'npm config get *', rule: 'Bash(npm config get *)' },
      { label: 'npm config list', rule: 'Bash(npm config list)' },
      { label: 'npm root *', rule: 'Bash(npm root *)' },
      { label: 'npm prefix *', rule: 'Bash(npm prefix *)' },
      { label: 'npm cache verify', rule: 'Bash(npm cache verify)' },
      { label: 'npm cache clean *', rule: 'Bash(npm cache clean *)' },
      { label: 'npm *', rule: 'Bash(npm *)', risk: 'wide' },
    ],
  },
  {
    id: 'pnpm',
    title: 'pnpm',
    description: 'pnpm',
    order: 3,
    selectAllLabel: 'pnpm',
    commands: [
      { label: 'pnpm --version', rule: 'Bash(pnpm --version)' },
      { label: 'pnpm install', rule: 'Bash(pnpm install)' },
      { label: 'pnpm install *', rule: 'Bash(pnpm install *)' },
      { label: 'pnpm i', rule: 'Bash(pnpm i)' },
      { label: 'pnpm i *', rule: 'Bash(pnpm i *)' },
      { label: 'pnpm run', rule: 'Bash(pnpm run)' },
      { label: 'pnpm run *', rule: 'Bash(pnpm run *)' },
      { label: 'pnpm test', rule: 'Bash(pnpm test)' },
      { label: 'pnpm test *', rule: 'Bash(pnpm test *)' },
      { label: 'pnpm start *', rule: 'Bash(pnpm start *)' },
      { label: 'pnpm build *', rule: 'Bash(pnpm build *)' },
      { label: 'pnpm list *', rule: 'Bash(pnpm list *)' },
      { label: 'pnpm ls *', rule: 'Bash(pnpm ls *)' },
      { label: 'pnpm view *', rule: 'Bash(pnpm view *)' },
      { label: 'pnpm outdated *', rule: 'Bash(pnpm outdated *)' },
      { label: 'pnpm audit *', rule: 'Bash(pnpm audit *)' },
      { label: 'pnpm exec *', rule: 'Bash(pnpm exec *)' },
      { label: 'pnpm dlx *', rule: 'Bash(pnpm dlx *)' },
      { label: 'pnpm *', rule: 'Bash(pnpm *)', risk: 'wide' },
    ],
  },
  {
    id: 'yarn',
    title: 'yarn',
    description: 'yarn',
    order: 4,
    selectAllLabel: 'yarn',
    commands: [
      { label: 'yarn --version', rule: 'Bash(yarn --version)' },
      { label: 'yarn install', rule: 'Bash(yarn install)' },
      { label: 'yarn install *', rule: 'Bash(yarn install *)' },
      { label: 'yarn run', rule: 'Bash(yarn run)' },
      { label: 'yarn run *', rule: 'Bash(yarn run *)' },
      { label: 'yarn test', rule: 'Bash(yarn test)' },
      { label: 'yarn test *', rule: 'Bash(yarn test *)' },
      { label: 'yarn start *', rule: 'Bash(yarn start *)' },
      { label: 'yarn build *', rule: 'Bash(yarn build *)' },
      { label: 'yarn list *', rule: 'Bash(yarn list *)' },
      { label: 'yarn info *', rule: 'Bash(yarn info *)' },
      { label: 'yarn outdated *', rule: 'Bash(yarn outdated *)' },
      { label: 'yarn audit *', rule: 'Bash(yarn audit *)' },
      { label: 'yarn cache *', rule: 'Bash(yarn cache *)' },
      { label: 'yarn *', rule: 'Bash(yarn *)', risk: 'wide' },
    ],
  },
  {
    id: 'bun',
    title: 'bun',
    description: 'bun',
    order: 5,
    selectAllLabel: 'bun',
    commands: [
      { label: 'bun --version', rule: 'Bash(bun --version)' },
      { label: 'bun install', rule: 'Bash(bun install)' },
      { label: 'bun install *', rule: 'Bash(bun install *)' },
      { label: 'bun add *', rule: 'Bash(bun add *)' },
      { label: 'bun remove *', rule: 'Bash(bun remove *)' },
      { label: 'bun run', rule: 'Bash(bun run)' },
      { label: 'bun run *', rule: 'Bash(bun run *)' },
      { label: 'bun test', rule: 'Bash(bun test)' },
      { label: 'bun test *', rule: 'Bash(bun test *)' },
      { label: 'bunx *', rule: 'Bash(bunx *)' },
      { label: 'bun build *', rule: 'Bash(bun build *)' },
      { label: 'bun pm *', rule: 'Bash(bun pm *)' },
      { label: 'bun *', rule: 'Bash(bun *)', risk: 'wide' },
    ],
  },
  {
    id: 'frontend',
    title: '前端工具链',
    description: '前端工具链',
    order: 6,
    selectAllLabel: '前端工具链',
    commands: [
      { label: 'npx tsc', rule: 'Bash(npx tsc *)' },
      { label: 'npx vite', rule: 'Bash(npx vite *)' },
      { label: 'npx eslint', rule: 'Bash(npx eslint *)' },
      { label: 'npx prettier', rule: 'Bash(npx prettier *)' },
      { label: 'npx tsx', rule: 'Bash(npx tsx *)' },
      { label: 'npx vitest', rule: 'Bash(npx vitest *)' },
      { label: 'npx playwright', rule: 'Bash(npx playwright *)' },
      { label: 'npx tailwindcss', rule: 'Bash(npx tailwindcss *)' },
      { label: 'npx next', rule: 'Bash(npx next *)' },
      { label: 'npx nuxt', rule: 'Bash(npx nuxt *)' },
      { label: 'npx astro', rule: 'Bash(npx astro *)' },
      { label: 'npx webpack', rule: 'Bash(npx webpack *)' },
      { label: 'npx rollup', rule: 'Bash(npx rollup *)' },
      { label: 'npx jest', rule: 'Bash(npx jest *)' },
      { label: 'npx cypress', rule: 'Bash(npx cypress *)' },
      { label: 'npx *', rule: 'Bash(npx *)', risk: 'wide' },
    ],
  },
  {
    id: 'git-readonly',
    title: 'Git 只读',
    description: 'Git 只读',
    order: 7,
    selectAllLabel: 'Git 只读',
    commands: [
      { label: 'git status', rule: 'Bash(git status)' },
      { label: 'git diff *', rule: 'Bash(git diff *)' },
      { label: 'git log *', rule: 'Bash(git log *)' },
      { label: 'git show *', rule: 'Bash(git show *)' },
      { label: 'git branch *', rule: 'Bash(git branch *)' },
      { label: 'git branch --all', rule: 'Bash(git branch --all)' },
      { label: 'git remote -v', rule: 'Bash(git remote -v)' },
      { label: 'git rev-parse *', rule: 'Bash(git rev-parse *)' },
      { label: 'git ls-files *', rule: 'Bash(git ls-files *)' },
      { label: 'git ls-remote *', rule: 'Bash(git ls-remote *)' },
      { label: 'git tag *', rule: 'Bash(git tag *)' },
      { label: 'git describe *', rule: 'Bash(git describe *)' },
      { label: 'git config --get *', rule: 'Bash(git config --get *)' },
      { label: 'git blame *', rule: 'Bash(git blame *)' },
      { label: 'git reflog *', rule: 'Bash(git reflog *)' },
    ],
  },
  {
    id: 'git-write',
    title: 'Git 写入',
    description: 'Git 写入',
    order: 8,
    selectAllLabel: 'Git 写入',
    commands: [
      { label: 'git add *', rule: 'Bash(git add *)' },
      { label: 'git commit *', rule: 'Bash(git commit *)' },
      { label: 'git checkout *', rule: 'Bash(git checkout *)' },
      { label: 'git switch *', rule: 'Bash(git switch *)' },
      { label: 'git restore *', rule: 'Bash(git restore *)' },
      { label: 'git stash *', rule: 'Bash(git stash *)' },
      { label: 'git merge *', rule: 'Bash(git merge *)' },
      { label: 'git rebase *', rule: 'Bash(git rebase *)' },
      { label: 'git cherry-pick *', rule: 'Bash(git cherry-pick *)' },
      { label: 'git revert *', rule: 'Bash(git revert *)' },
      { label: 'git pull *', rule: 'Bash(git pull *)' },
      { label: 'git fetch *', rule: 'Bash(git fetch *)' },
      { label: 'git push *', rule: 'Bash(git push *)', risk: 'high' },
      { label: 'git reset *', rule: 'Bash(git reset *)', risk: 'high' },
      { label: 'git clean *', rule: 'Bash(git clean *)', risk: 'high' },
    ],
  },
  {
    id: 'python-pip',
    title: 'Python / pip',
    description: 'Python / pip',
    order: 9,
    selectAllLabel: 'Python / pip',
    commands: [
      { label: 'python --version', rule: 'Bash(python --version)' },
      { label: 'python3 --version', rule: 'Bash(python3 --version)' },
      { label: 'python *', rule: 'Bash(python *)', risk: 'wide' },
      { label: 'python3 *', rule: 'Bash(python3 *)', risk: 'wide' },
      { label: 'pip --version', rule: 'Bash(pip --version)' },
      { label: 'pip list *', rule: 'Bash(pip list *)' },
      { label: 'pip show *', rule: 'Bash(pip show *)' },
      { label: 'pip install *', rule: 'Bash(pip install *)' },
      { label: 'pip uninstall *', rule: 'Bash(pip uninstall *)' },
      { label: 'pip freeze', rule: 'Bash(pip freeze)' },
      { label: 'pip check', rule: 'Bash(pip check)' },
      { label: 'pip config get *', rule: 'Bash(pip config get *)' },
      { label: 'pip config list', rule: 'Bash(pip config list)' },
      { label: 'pip *', rule: 'Bash(pip *)', risk: 'wide' },
      { label: 'pytest *', rule: 'Bash(pytest *)' },
      { label: 'python -m pytest *', rule: 'Bash(python -m pytest *)' },
      { label: 'python -m pip *', rule: 'Bash(python -m pip *)' },
    ],
  },
  {
    id: 'uv-poetry',
    title: 'uv / Poetry',
    description: 'uv / Poetry',
    order: 10,
    selectAllLabel: 'uv / Poetry',
    commands: [
      { label: 'uv --version', rule: 'Bash(uv --version)' },
      { label: 'uv run *', rule: 'Bash(uv run *)' },
      { label: 'uv pip install *', rule: 'Bash(uv pip install *)' },
      { label: 'uv pip uninstall *', rule: 'Bash(uv pip uninstall *)' },
      { label: 'uv pip list *', rule: 'Bash(uv pip list *)' },
      { label: 'uv sync *', rule: 'Bash(uv sync *)' },
      { label: 'uv add *', rule: 'Bash(uv add *)' },
      { label: 'uv remove *', rule: 'Bash(uv remove *)' },
      { label: 'uv lock *', rule: 'Bash(uv lock *)' },
      { label: 'uv tree *', rule: 'Bash(uv tree *)' },
      { label: 'uv *', rule: 'Bash(uv *)', risk: 'wide' },
      { label: 'poetry --version', rule: 'Bash(poetry --version)' },
      { label: 'poetry install *', rule: 'Bash(poetry install *)' },
      { label: 'poetry run *', rule: 'Bash(poetry run *)' },
      { label: 'poetry add *', rule: 'Bash(poetry add *)' },
      { label: 'poetry remove *', rule: 'Bash(poetry remove *)' },
      { label: 'poetry show *', rule: 'Bash(poetry show *)' },
      { label: 'poetry lock *', rule: 'Bash(poetry lock *)' },
      { label: 'poetry update *', rule: 'Bash(poetry update *)' },
      { label: 'poetry *', rule: 'Bash(poetry *)', risk: 'wide' },
    ],
  },
  {
    id: 'rust-cargo',
    title: 'Rust / Cargo',
    description: 'Rust / Cargo',
    order: 11,
    selectAllLabel: 'Rust / Cargo',
    commands: [
      { label: 'rustc --version', rule: 'Bash(rustc --version)' },
      { label: 'cargo --version', rule: 'Bash(cargo --version)' },
      { label: 'cargo check *', rule: 'Bash(cargo check *)' },
      { label: 'cargo build *', rule: 'Bash(cargo build *)' },
      { label: 'cargo test *', rule: 'Bash(cargo test *)' },
      { label: 'cargo run *', rule: 'Bash(cargo run *)' },
      { label: 'cargo fmt *', rule: 'Bash(cargo fmt *)' },
      { label: 'cargo clippy *', rule: 'Bash(cargo clippy *)' },
      { label: 'cargo tree *', rule: 'Bash(cargo tree *)' },
      { label: 'cargo metadata *', rule: 'Bash(cargo metadata *)' },
      { label: 'cargo update *', rule: 'Bash(cargo update *)' },
      { label: 'cargo clean', rule: 'Bash(cargo clean)' },
      { label: 'cargo add *', rule: 'Bash(cargo add *)' },
      { label: 'cargo remove *', rule: 'Bash(cargo remove *)' },
      { label: 'cargo install *', rule: 'Bash(cargo install *)' },
      { label: 'cargo doc *', rule: 'Bash(cargo doc *)' },
      { label: 'cargo *', rule: 'Bash(cargo *)', risk: 'wide' },
    ],
  },
  {
    id: 'go',
    title: 'Go',
    description: 'Go',
    order: 12,
    selectAllLabel: 'Go',
    commands: [
      { label: 'go version', rule: 'Bash(go version)' },
      { label: 'go env *', rule: 'Bash(go env *)' },
      { label: 'go mod tidy', rule: 'Bash(go mod tidy)' },
      { label: 'go mod download', rule: 'Bash(go mod download)' },
      { label: 'go mod graph', rule: 'Bash(go mod graph)' },
      { label: 'go mod init *', rule: 'Bash(go mod init *)' },
      { label: 'go list *', rule: 'Bash(go list *)' },
      { label: 'go build *', rule: 'Bash(go build *)' },
      { label: 'go test *', rule: 'Bash(go test *)' },
      { label: 'go run *', rule: 'Bash(go run *)' },
      { label: 'go vet *', rule: 'Bash(go vet *)' },
      { label: 'go fmt *', rule: 'Bash(go fmt *)' },
      { label: 'go generate *', rule: 'Bash(go generate *)' },
      { label: 'go install *', rule: 'Bash(go install *)' },
      { label: 'go *', rule: 'Bash(go *)', risk: 'wide' },
    ],
  },
  {
    id: 'java-maven-gradle',
    title: 'Java / Maven / Gradle',
    description: 'Java / Maven / Gradle',
    order: 13,
    selectAllLabel: 'Java / Maven / Gradle',
    commands: [
      { label: 'java -version', rule: 'Bash(java -version)' },
      { label: 'javac -version', rule: 'Bash(javac -version)' },
      { label: 'mvn -version', rule: 'Bash(mvn -version)' },
      { label: 'mvn test *', rule: 'Bash(mvn test *)' },
      { label: 'mvn package *', rule: 'Bash(mvn package *)' },
      { label: 'mvn install *', rule: 'Bash(mvn install *)' },
      { label: 'mvn clean *', rule: 'Bash(mvn clean *)' },
      { label: 'mvn compile *', rule: 'Bash(mvn compile *)' },
      { label: 'mvn verify *', rule: 'Bash(mvn verify *)' },
      { label: 'mvn *', rule: 'Bash(mvn *)', risk: 'wide' },
      { label: 'gradle -version', rule: 'Bash(gradle -version)' },
      { label: 'gradle build *', rule: 'Bash(gradle build *)' },
      { label: 'gradle test *', rule: 'Bash(gradle test *)' },
      { label: 'gradle run *', rule: 'Bash(gradle run *)' },
      { label: 'gradle clean *', rule: 'Bash(gradle clean *)' },
      { label: 'gradle *', rule: 'Bash(gradle *)', risk: 'wide' },
      { label: './gradlew build *', rule: 'Bash(./gradlew build *)' },
      { label: './gradlew test *', rule: 'Bash(./gradlew test *)' },
      { label: './gradlew run *', rule: 'Bash(./gradlew run *)' },
      { label: './gradlew clean *', rule: 'Bash(./gradlew clean *)' },
      { label: './gradlew *', rule: 'Bash(./gradlew *)', risk: 'wide' },
    ],
  },
  {
    id: 'c-cpp-cmake',
    title: 'C / C++ / CMake / Make',
    description: 'C / C++ / CMake / Make',
    order: 14,
    selectAllLabel: 'C / C++ / CMake / Make',
    commands: [
      { label: 'gcc --version', rule: 'Bash(gcc --version)' },
      { label: 'g++ --version', rule: 'Bash(g++ --version)' },
      { label: 'clang --version', rule: 'Bash(clang --version)' },
      { label: 'clang++ --version', rule: 'Bash(clang++ --version)' },
      { label: 'cmake --version', rule: 'Bash(cmake --version)' },
      { label: 'cmake *', rule: 'Bash(cmake *)', risk: 'wide' },
      { label: 'make', rule: 'Bash(make)' },
      { label: 'make *', rule: 'Bash(make *)', risk: 'wide' },
      { label: 'make test *', rule: 'Bash(make test *)' },
      { label: 'ninja', rule: 'Bash(ninja)' },
      { label: 'ninja *', rule: 'Bash(ninja *)' },
      { label: 'meson *', rule: 'Bash(meson *)' },
      { label: 'ctest *', rule: 'Bash(ctest *)' },
    ],
  },
  {
    id: 'dotnet',
    title: '.NET',
    description: '.NET',
    order: 15,
    selectAllLabel: '.NET',
    commands: [
      { label: 'dotnet --version', rule: 'Bash(dotnet --version)' },
      { label: 'dotnet restore *', rule: 'Bash(dotnet restore *)' },
      { label: 'dotnet build *', rule: 'Bash(dotnet build *)' },
      { label: 'dotnet test *', rule: 'Bash(dotnet test *)' },
      { label: 'dotnet run *', rule: 'Bash(dotnet run *)' },
      { label: 'dotnet publish *', rule: 'Bash(dotnet publish *)' },
      { label: 'dotnet clean *', rule: 'Bash(dotnet clean *)' },
      { label: 'dotnet new *', rule: 'Bash(dotnet new *)' },
      { label: 'dotnet add *', rule: 'Bash(dotnet add *)' },
      { label: 'dotnet remove *', rule: 'Bash(dotnet remove *)' },
      { label: 'dotnet *', rule: 'Bash(dotnet *)', risk: 'wide' },
    ],
  },
  {
    id: 'docker-compose',
    title: 'Docker / Compose',
    description: 'Docker / Compose',
    order: 16,
    selectAllLabel: 'Docker / Compose',
    commands: [
      { label: 'docker --version', rule: 'Bash(docker --version)' },
      { label: 'docker ps *', rule: 'Bash(docker ps *)' },
      { label: 'docker images *', rule: 'Bash(docker images *)' },
      { label: 'docker logs *', rule: 'Bash(docker logs *)' },
      { label: 'docker inspect *', rule: 'Bash(docker inspect *)' },
      { label: 'docker compose ps *', rule: 'Bash(docker compose ps *)' },
      { label: 'docker compose logs *', rule: 'Bash(docker compose logs *)' },
      { label: 'docker compose build *', rule: 'Bash(docker compose build *)' },
      { label: 'docker compose up *', rule: 'Bash(docker compose up *)' },
      { label: 'docker compose down *', rule: 'Bash(docker compose down *)' },
      { label: 'docker compose restart *', rule: 'Bash(docker compose restart *)' },
      { label: 'docker build *', rule: 'Bash(docker build *)' },
      { label: 'docker run *', rule: 'Bash(docker run *)', risk: 'high' },
      { label: 'docker stop *', rule: 'Bash(docker stop *)' },
      { label: 'docker rm *', rule: 'Bash(docker rm *)' },
      { label: 'docker *', rule: 'Bash(docker *)', risk: 'wide' },
      { label: 'docker compose *', rule: 'Bash(docker compose *)', risk: 'wide' },
    ],
  },
  {
    id: 'network-debug',
    title: '网络与调试',
    description: '网络与调试',
    order: 17,
    selectAllLabel: '网络与调试',
    commands: [
      { label: 'curl *', rule: 'Bash(curl *)' },
      { label: 'wget *', rule: 'Bash(wget *)' },
      { label: 'ping *', rule: 'Bash(ping *)' },
      { label: 'nslookup *', rule: 'Bash(nslookup *)' },
      { label: 'dig *', rule: 'Bash(dig *)' },
      { label: 'lsof *', rule: 'Bash(lsof *)' },
      { label: 'lsof -i *', rule: 'Bash(lsof -i *)' },
      { label: 'netstat *', rule: 'Bash(netstat *)' },
      { label: 'ps *', rule: 'Bash(ps *)' },
      { label: 'ps aux', rule: 'Bash(ps aux)' },
      { label: 'top *', rule: 'Bash(top *)' },
      { label: 'htop *', rule: 'Bash(htop *)' },
      { label: 'kill *', rule: 'Bash(kill *)', risk: 'high' },
      { label: 'kill -9 *', rule: 'Bash(kill -9 *)', risk: 'high' },
    ],
  },
  {
    id: 'macos-unix',
    title: 'macOS / Unix 辅助',
    description: 'macOS / Unix 辅助',
    order: 18,
    selectAllLabel: 'macOS / Unix 辅助',
    commands: [
      { label: 'open *', rule: 'Bash(open *)' },
      { label: 'pbcopy', rule: 'Bash(pbcopy)' },
      { label: 'pbpaste', rule: 'Bash(pbpaste)' },
      { label: 'xcodebuild *', rule: 'Bash(xcodebuild *)' },
      { label: 'swift --version', rule: 'Bash(swift --version)' },
      { label: 'swift build *', rule: 'Bash(swift build *)' },
      { label: 'swift test *', rule: 'Bash(swift test *)' },
      { label: 'brew --version', rule: 'Bash(brew --version)' },
      { label: 'brew list *', rule: 'Bash(brew list *)' },
      { label: 'brew info *', rule: 'Bash(brew info *)' },
    ],
  },
  {
    id: 'custom',
    title: '自定义命令',
    description: '自定义命令',
    order: 19,
    selectAllLabel: '自定义命令',
    commands: [],
  },
];

export const ALL_BASH_COMMAND_RULES: Set<string> = new Set(
  BASH_COMMAND_GROUPS.flatMap((g) => g.commands.map((c) => c.rule))
);

export const WIDE_MATCH_RULES: Set<string> = new Set(
  BASH_COMMAND_GROUPS.flatMap((g) => g.commands.filter((c) => c.risk === 'wide').map((c) => c.rule))
);

export const DANGEROUS_BASH_RULES: Set<string> = new Set([
  ...BASH_COMMAND_GROUPS.flatMap((g) => g.commands.filter((c) => c.risk === 'high').map((c) => c.rule)),
  'Bash(sudo *)',
  'Bash(su *)',
  'Bash(rm -rf /)',
  'Bash(rm -rf ~)',
  'Bash(rm -rf ./*)',
  'Bash(git push --force*)',
  'Bash(git reset --hard *)',
  'Bash(git clean -fd *)',
  'Bash(ssh *)',
  'Bash(scp *)',
  'Bash(rsync *)',
  'Bash(docker run --privileged *)',
  'Bash(docker system prune *)',
  'Bash(docker volume rm *)',
  'Bash(docker compose down -v *)',
]);
