import { AppState } from './types';
import { defaultDenyRules, defaultSandbox, defaultFilesystem, devDomains } from './defaults';

export type ProfileId = 'strict' | 'safe-dev' | 'automation' | 'custom';

interface ProfileDef {
  id: ProfileId;
  name: string;
  description: string;
  apply?: (state: AppState) => AppState;
}

export const profiles: ProfileDef[] = [
  {
    id: 'strict',
    name: 'Strict Review Mode',
    description: 'Offline review, minimal auto-permissions, more operations require manual confirmation',
    apply: (state) => ({
      ...state,
      defaultMode: 'default',
      askEnabled: true,
      agentTeamsEnabled: false,
      sandbox: {
        ...defaultSandbox,
        enabled: true,
        failIfUnavailable: true,
        autoAllowBashIfSandboxed: false,
        allowUnsandboxedCommands: false,
      },
      filesystem: { ...defaultFilesystem },
      network: { allowedDomains: [], deniedDomains: ['*'], allowLocalBinding: true, allowAllUnixSockets: false },
      networkMode: 'disabled',
      webfetchMode: 'deny-all',
      webfetchCustomDomains: [],
      websearchMode: 'deny',
      permissions: {
        allow: [
          'Read(./**)',
          'Bash(pwd)',
          'Bash(ls *)',
          'Bash(find . *)',
          'Bash(grep *)',
          'Bash(git status)',
          'Bash(git diff *)',
          'Bash(git log *)',
          'Glob',
          'Grep',
        ],
        ask: ['Edit', 'Write', 'Bash', 'Task', 'Monitor', 'PowerShell', 'mcp__server__tool'],
        deny: [...defaultDenyRules, 'WebFetch', 'WebSearch'],
      },
      activeProfile: 'strict',
    }),
  },
  {
    id: 'safe-dev',
    name: 'Safe Network Dev Mode',
    description: 'Open dev network whitelist, suitable for daily project iteration',
    apply: (state) => ({
      ...state,
      defaultMode: 'acceptEdits',
      askEnabled: true,
      agentTeamsEnabled: false,
      sandbox: {
        ...defaultSandbox,
        enabled: true,
        failIfUnavailable: true,
        autoAllowBashIfSandboxed: true,
        allowUnsandboxedCommands: false,
      },
      filesystem: { ...defaultFilesystem },
      network: { allowedDomains: [...devDomains], deniedDomains: [], allowLocalBinding: true, allowAllUnixSockets: false },
      networkMode: 'dev-domains',
      webfetchMode: 'dev-docs',
      webfetchCustomDomains: [],
      websearchMode: 'ask',
      permissions: {
        allow: [
          'Read(./**)',
          'Edit(./**)',
          'Write(./**)',
          'Bash(pwd)',
          'Bash(ls *)',
          'Bash(find . *)',
          'Bash(grep *)',
          'Bash(which *)',
          'Bash(echo *)',
          'Bash(git status)',
          'Bash(git diff *)',
          'Bash(git log *)',
          'Bash(npm install)',
          'Bash(npm run *)',
          'Bash(npm test *)',
          'Bash(pnpm install)',
          'Bash(pnpm run *)',
          'Bash(yarn install)',
          'Bash(yarn run *)',
          'Bash(cargo check *)',
          'Bash(cargo build *)',
          'Bash(cargo test *)',
          'Glob',
          'Grep',
          'Monitor',
        ],
        ask: ['Task', 'PowerShell', 'mcp__server__tool'],
        deny: [...defaultDenyRules],
      },
      activeProfile: 'safe-dev',
    }),
  },
  {
    id: 'automation',
    name: 'Automation Mode',
    description: 'Maximize dev automation, keep host and sensitive operation safeguards',
    apply: (state) => ({
      ...state,
      defaultMode: 'auto',
      askEnabled: false,
      agentTeamsEnabled: false,
      sandbox: {
        ...defaultSandbox,
        enabled: true,
        failIfUnavailable: true,
        autoAllowBashIfSandboxed: true,
        allowUnsandboxedCommands: false,
      },
      filesystem: { ...defaultFilesystem },
      network: { allowedDomains: ['*'], deniedDomains: [], allowLocalBinding: true, allowAllUnixSockets: false },
      networkMode: 'open',
      webfetchMode: 'all',
      webfetchCustomDomains: [],
      websearchMode: 'allow',
      permissions: {
        allow: [
          'Read(./**)',
          'Edit(./**)',
          'Write(./**)',
          'Glob',
          'Grep',
          'Monitor',
          'Task',
          'WebSearch',
          'Bash(pwd)',
          'Bash(ls *)',
          'Bash(find . *)',
          'Bash(grep *)',
          'Bash(rg *)',
          'Bash(which *)',
          'Bash(echo *)',
          'Bash(cat *)',
          'Bash(head *)',
          'Bash(tail *)',
          'Bash(tree *)',
          'Bash(mkdir *)',
          'Bash(mkdir -p *)',
          'Bash(touch *)',
          'Bash(cp *)',
          'Bash(mv *)',
          'Bash(git status)',
          'Bash(git diff *)',
          'Bash(git log *)',
          'Bash(git show *)',
          'Bash(git branch *)',
          'Bash(git fetch *)',
          'Bash(git pull *)',
          'Bash(npm *)',
          'Bash(pnpm *)',
          'Bash(yarn *)',
          'Bash(bun *)',
          'Bash(npx *)',
          'Bash(python *)',
          'Bash(python3 *)',
          'Bash(pip *)',
          'Bash(uv *)',
          'Bash(poetry *)',
          'Bash(cargo *)',
          'Bash(go *)',
          'Bash(mvn *)',
          'Bash(gradle *)',
          'Bash(./gradlew *)',
          'Bash(make *)',
          'Bash(cmake *)',
          'Bash(dotnet *)',
          'Bash(docker ps *)',
          'Bash(docker images *)',
          'Bash(docker logs *)',
          'Bash(docker inspect *)',
          'Bash(docker compose ps *)',
          'Bash(docker compose logs *)',
          'Bash(docker compose build *)',
        ],
        ask: [],
        deny: [...defaultDenyRules],
      },
      activeProfile: 'automation',
    }),
  },
  {
    id: 'custom',
    name: 'Custom Mode',
    description: 'Manually combine all configuration options',
  },
];

export function applyProfile(state: AppState, profileId: ProfileId): AppState {
  const profile = profiles.find((p) => p.id === profileId);
  if (!profile || !profile.apply) return { ...state, activeProfile: profileId };
  return profile.apply(state);
}
